version: '2'
services:
  tws:
    build: .
    #image: dvasdekis/ib-gateway-docker:v978
    volumes:
      - ./ib/IBController.ini:/root/IBController/IBController.ini
      - ./ib/jts.ini:/root/Jts/jts.ini
    environment:
      - TRADING_MODE=${TWS_TRADING_MODE}
      - TWSUSERID=${TWS_USER_ID}
      - TWSPASSWORD=${TWS_PASSWORD}
      - FIXUSERID=
      - FIXPASSWORD=
      - XVFB_ARGS="-ac -screen 0 1024x768x16 +extension RANDR"
#   Uncomment the below to use VNC
#    ports:
#      - 5901:5900
