version: '2'
services:
  tws:
    build: .
    #image: dvasdekis/ib-gateway-docker:v978
    environment:
      - TRADING_MODE=${TWS_TRADING_MODE}
      - TWSUSERID=${TWS_USER_ID}
      - TWSPASSWORD=${TWS_PASSWORD}
      - VNC_PASSWORD=sgym7y9h57wkfha
      - FIXUSERID=
      - FIXPASSWORD=